server:
  port: 8080

spring:
  application:
    name: nacos-client-8080 #spring应用名
  cloud:
    nacos:
      #Nacos作为注册中心的配置项 对应NacosDiscoveryProperties配置类
      discovery:
        server-addr: localhost:8848 # Nacos服务地址
        service: ${spring.application.name} #注册到Nacos的服务名 默认应用名
management:
  endpoints:
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。

  endpoint:
    health:
      enabled: true
      show-details: always
