server:
  port: 8080

spring:
  application:
    name: nacos-client-8080 #spring应用名
  cloud:
    nacos:
      #Nacos作为注册中心的配置项 对应NacosDiscoveryProperties配置类
      discovery:
        server-addr: localhost:8848 # Nacos服务地址
        service: ${spring.application.name} #注册到Nacos的服务名 默认应用名

management:
  endpoints:
    web:
      base-path: /actuator #默认API根目录
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
        exclude:  # 关闭的端口 * 排除所有
  endpoint:
    health: # Health 端点配置项，对应 HealthProperties 配置类
      enabled: true
      show-details: always
  # DiskSpaceHealthIndicator 配置项，对应 DiskSpaceHealthIndicatorProperties
  health:
    diskspace:
      enabled: true

# Dubbo 配置项，对应 DubboConfigurationProperties 类
dubbo:
  scan:
    base-packages: com.xx.cloud.service # 指定 Dubbo 服务实现类的扫描基准包
  # Dubbo 服务暴露的协议配置，对应 ProtocolConfig Map
  protocols:
    dubbo:
      name: dubbo # 协议名称
      port: -1 # 协议端口，-1 表示自增端口，从 20880 开始
  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
  registry:
    address: spring-cloud://127.0.0.1:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
  cloud:
    subscribed-services: '' # 设置订阅的应用列表，默认为 * 订阅所有应用
